### ISSUE TITLE
مشکل در نسخه هاست

### ISSUE THREAD

**Issue by tbehzad76** [x0sina/marzban-sub#14]
در نسخه هاست یوزر رو غیر فعال نشون میده و لینک ساب رو که توی نرم افزار v2rayng اد میکنی اپدیت نمیشه
همچنین توی ios هم توی نرم افزار streisand لیست کافیگ ها رو نمیاره

**Comment by tbehzad76** [comment]
دوباره تست کردم همچنان مشکل هست
من نسخه هاست رو همین امروز نصب کردم ولی اخرین ابدیت این نسخه مال 2 هفته پیشه

**Comment by x0sina** [comment]
نسخه هاست کاملا تست شده اوکی هستش و کار میکنه ممکنه فایل htaacess رو اپلود نکرده باشی

**Comment by tbehzad76** [comment]
htaccess هم چک کردم اپلود شده
