### ISSUE TITLE
مشکل با فوروارد سابسکریپشن

### ISSUE THREAD

**Issue by irluca** [x0sina/marzban-sub#2]
سلام
من سابسکریپشن رو طبق این آموزش:
https://github.com/Gozargah/Marzban/discussions/26
روی یک هاست ایرانی فوروارد کردم 
حالا که از تمپلت شما میخوام استفاده کنم، هیچ تغییری ایجاد نمیشه و صفحه تمپلت بالا نمیاد.
روی یک سروری که ساب رو فوروارد نکردم بدون مشکل کار میکنه.
میشه راهنمایی کنید باید چیکار کنم؟

**Comment by x0sina** [comment]
سلام
لطفا آخرین نسخه رو جایگزین کنید و اگه روی سروری که فوروارد نکردید به درستی کار میکنه و روی هاست ایرانی باز نمیکنه فک نکنم مشکلتون از تمپلیت باشه و فوروارد کردن هاست ایرانتونو چک کنید.
